<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Homelab.Domain\Homelab.Domain.csproj" />
    <ProjectReference Include="..\Homelab.Api.Ef\Homelab.Api.Ef.csproj" />
    <ProjectReference Include="..\Homelab.Api.MongoDb\Homelab.Api.MongoDb.csproj" />
  </ItemGroup>

</Project>
