<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e5ca6346-6fc5-4bf3-aeb6-7450eac1c2a0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiServices\Homelab.Api\Homelab.Api.csproj" />
    <ProjectReference Include="..\WebServices\Homelab.Web\Homelab.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.3.5" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.5" />
  </ItemGroup>

</Project>
